### PR TITLE
Add ability to customise specified sats amount in QR code

### PR DESCRIPTION
**Pull request by RonanJackson**
Implements https://github.com/GaloyMoney/lnpage/issues/40

**Changes**
If the user navigates to the route: `/:username/:amountInSats` the UI will generate a QR code with the number automatically filling the value of the transaction in the lightning wallet.

Screenshot 2021-09-26 at 8 43 10 pm
Screenshot 2021-09-26 at 8 43 00 pm

### CODE REVIEW

**Comment by samerbuna** [comment]
Thanks for working on this @RonanJackson, it's good as is but if you feel like improving it a bit, I'd go with a new component, `ReceiveAmount`, and maybe introduce a component `ReceiveNoAmount` keeping the `Receive` component as the wrapper for both of them (to host the layout, for example).

If you want, we can pair on this tomorrow.

**Comment by RonanJackson** [comment]
> Thanks for working on this @RonanJackson, it's good as is but if you feel like improving it a bit, I'd go with a new component, `ReceiveAmount`, and maybe introduce a component `ReceiveNoAmount` keeping the `Receive` component as the wrapper for both of them (to host the layout, for example).
> 
> If you want, we can pair on this tomorrow.

I was torn whether to do this as it would duplicate a lot of functionality. I changed my mind :)

It is now in two classes, but unsure how to best merge them into a shared parent class. Will have a think. Lots of duplicated code right now here.

**Comment by RonanJackson** [comment]
> > Thanks for working on this @RonanJackson, it's good as is but if you feel like improving it a bit, I'd go with a new component, `ReceiveAmount`, and maybe introduce a component `ReceiveNoAmount` keeping the `Receive` component as the wrapper for both of them (to host the layout, for example).
> > If you want, we can pair on this tomorrow.
> 
> I was torn whether to do this as it would duplicate a lot of functionality. I changed my mind :)
> 
> It is now in two classes, but unsure how to best merge them into a shared parent class. Will have a think. Lots of duplicated code right now here.
> 
> Let me know your thoughts. Happy to pair later if I get time!

Implemented a refactor with a shared component, I think this is what you meant. Seems like the best solution I think.

**Review by samerbuna — COMMENTED** [review]
This looks great! Thanks.

I'll test and deploy today.

**Comment by RonanJackson** [comment]
> This looks great! Thanks.
> 
> I'll test and deploy today.

Need anything more from me on this one?

**Pull request merged**
